### ISSUE TITLE
Move checker functions for individual columns from `cli.py` into a separate helper module

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/bagelbids#59]
- [x] Functions like `is_missing_value`, `is_column_categorical`, `map_cat_val_to_term` should live in separate module for improved organization of imports, tests, etc. The same goes for the corresponding tests.
- [x] #52 (refactor corresponding tests into their own test suite)

**Comment by alyssadai** [comment]
@surchs are you on board with moving all functions in `cli.py` aside from [load_json](https://github.com/neurobagel/bagelbids/blob/377c94c88c3f20d68d16eeac6c6ae1680424fe0e/bagelbids/cli.py#L181-L183) and the main `pheno` command into a `utility.py`?

Alternatively, we could also still keep [validate_inputs](https://github.com/neurobagel/bagelbids/blob/377c94c88c3f20d68d16eeac6c6ae1680424fe0e/bagelbids/cli.py#L193) inside the `cli` module as well.

**Comment by surchs** [comment]
In my mind, we'll end up with something like this at the end:

- `cli.py` that is just a the typer app and the subcommands we're adding, e.g. `app.add_commands([pheno, bids])` or something like that
- `cmd_pheno.py` that is the pheno command and all the unique functions it is using
- `cmd_bids.py` that is the bids command and all the unique functions it is using
- `utility.py` that is a module with helper functions that both `bids` and `pheno` share

I'm not sure how many of the functions are / can be reused across the commands. But where possible, we should of course do that. But I wouldn't just default put everything in one module because that will make it tricky to say what this module is about (i.e. "functions?"). For now it may be better to leave the command-specific functions with the command module (e.g. `cmd_pheno.py`) and refactor them into a specialized module when they are useful somewhere else.

What do you think?
