### ISSUE TITLE
Write e2e test for pheno subcommand using example_synthetic

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/bagelbids#74]
Given `example_synthetic.json` and `example_synthetic.tsv`, the contents of the generated .jsonld should match that in `example_synthetic.jsonld`.

- [ ] update .json and .tsv for this example to pre-define the dataset and subject UUIDs (otherwise the ones randomly generated during the test won't match the IDs in the provided .jsonld)

**Comment by alyssadai** [comment]
@surchs thoughts on the UUID issue? My proposed approach is a little bit brute force but I'm not sure if we're currently planning to handle user-defined UUIDs.

**Comment by surchs** [comment]
The UUIDs are not meant to be persistent and shouldn't be used to address specific data because they are expected to change every time you make a new instance of the dataset. The main reason we have them now is so we don't have blank nodes in the graph (i.e. nodes with no identifier) because for those Stardog has to come up with random ids - and it doesn't always do so in a way that doesn't lead to id clashes. 

So the short answer is: I don't think there is a point in writing a test to make sure that the output is an identical copy of the example file, including the UUIDs.

**Comment by alyssadai** [comment]
Makes sense. Closing this issue in that case!
